version: 2.1
jobs:
  deploy-website:
    docker:
      - image: circleci/node:10.20.1
    steps:
      - checkout
      - run:
          name: Deploying to Github pages
          command: |
            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "$GIT_USER"
            echo "machine github.com login $GIT_USER password $GIT_TOKEN" > ~/.netrc
            cd website
            yarn install
            ORGANIZATION_NAME="cafienne" PROJECT_NAME="cafienne.github.io" CUSTOM_COMMIT_MESSAGE="Deploy website" GIT_USER=$GIT_USER yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only:
                - master
                - circleci-setup